CREATE TABLE `multi_buildings` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`street_number` text,
	`street_name` text,
	`address` text NOT NULL,
	`city` text DEFAULT 'Saskatoon',
	`postal` text,
	`building_name` text,
	`cmhc_zone` text,
	`region` text,
	`units` integer,
	`zoning` text,
	`year_built` integer,
	`assessed_value` integer,
	`building_owner` text,
	`parcel_number` text,
	`title_value` integer,
	`title_transfer_date` text,
	`property_manager` text,
	`manager_contact` text,
	`property_owner` text,
	`owner_contact` text,
	`owner_email` text,
	`construction_class` text,
	`bach_rent_low` real,
	`bach_rent_high` real,
	`bach_sf` integer,
	`one_bed_rent_low` real,
	`one_bed_rent_high` real,
	`one_bed_sf` integer,
	`two_bed_rent_low` real,
	`two_bed_rent_high` real,
	`two_bed_sf` integer,
	`three_bed_rent_low` real,
	`three_bed_rent_high` real,
	`three_bed_sf` integer,
	`rent_source` text,
	`contact_info` integer DEFAULT 0,
	`contact_date` text,
	`comments` text,
	`is_condo` integer DEFAULT 0,
	`is_sales_comp` integer DEFAULT 0,
	`updated_at` text
);
--> statement-breakpoint
CREATE INDEX `idx_multi_buildings_region` ON `multi_buildings` (`region`);--> statement-breakpoint
CREATE INDEX `idx_multi_buildings_owner` ON `multi_buildings` (`building_owner`);--> statement-breakpoint
CREATE INDEX `idx_multi_buildings_address` ON `multi_buildings` (`address`);