-- Add pending_comps table for email intake processing
CREATE TABLE `pending_comps` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`type` text NOT NULL,
	`property_type` text,
	`investment_type` text,
	`lease_type` text,
	`property_name` text,
	`address` text NOT NULL,
	`unit` text,
	`city` text DEFAULT 'Saskatoon',
	`province` text DEFAULT 'Saskatchewan',
	`seller` text,
	`purchaser` text,
	`landlord` text,
	`tenant` text,
	`portfolio` text,
	`sale_date` text,
	`sale_price` real,
	`price_psf` real,
	`price_per_acre` real,
	`is_renewal` integer,
	`lease_start` text,
	`lease_expiry` text,
	`term_months` integer,
	`net_rent_psf` real,
	`annual_rent` real,
	`rent_steps` text,
	`area_sf` real,
	`office_sf` real,
	`ceiling_height` real,
	`loading_docks` integer,
	`drive_in_doors` integer,
	`land_acres` real,
	`land_sf` real,
	`year_built` integer,
	`zoning` text,
	`noi` real,
	`cap_rate` real,
	`stabilized_noi` real,
	`stabilized_cap_rate` real,
	`vacancy_rate` real,
	`price_per_unit` real,
	`opex_ratio` real,
	`num_units` integer,
	`num_buildings` integer,
	`num_stories` integer,
	`construction_class` text,
	`retail_sales_per_annum` real,
	`retail_sales_psf` real,
	`operating_cost` real,
	`improvement_allowance` text,
	`free_rent_period` text,
	`fixturing_period` text,
	`comments` text,
	`source` text,
	`roll_number` text,
	`ppt_code` integer,
	`ppt_descriptor` text,
	`arms_length` integer,
	`retail_tenant_id` integer,
	`property_id` integer,
	`seller_company_id` integer,
	`purchaser_company_id` integer,
	`landlord_company_id` integer,
	`tenant_company_id` integer,
	`researched_unavailable` integer DEFAULT 0,
	`researched_at` text,
	`researched_by` integer,
	`address_normalized` text,
	`city_normalized` text,
	`source_type` text NOT NULL,
	`source_ref` text NOT NULL,
	`status` text DEFAULT 'pending' NOT NULL,
	`duplicate_of_id` integer,
	`confidence` real DEFAULT 0.5 NOT NULL,
	`field_confidence` text,
	`missing_fields` text,
	`notes` text,
	`reviewed_at` text,
	`reviewed_by` integer,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	FOREIGN KEY (`property_id`) REFERENCES `properties`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`seller_company_id`) REFERENCES `companies`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`purchaser_company_id`) REFERENCES `companies`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`landlord_company_id`) REFERENCES `companies`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`tenant_company_id`) REFERENCES `companies`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`duplicate_of_id`) REFERENCES `comps`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`reviewed_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);

-- Create indexes
CREATE INDEX `idx_pending_comps_status` ON `pending_comps` (`status`);
CREATE INDEX `idx_pending_comps_source_type` ON `pending_comps` (`source_type`);
CREATE INDEX `idx_pending_comps_confidence` ON `pending_comps` (`confidence`);
CREATE INDEX `idx_pending_comps_address` ON `pending_comps` (`address`);
CREATE INDEX `idx_pending_comps_duplicate_of_id` ON `pending_comps` (`duplicate_of_id`);